#------------------------------------------------------------------------------

#informacoes: 

#O aplicativo cli faz parte do projeto Dartpedia.

#o cli eh o nosso primeiro aplicativo desenvolvido usando o Dart

#pubspec.yaml - fica localizado na pasta dartpedia, em /dartpedia/cli

#outras informacoes sobre o cli,nosso aplicativo: 

#site:

#Autor:Maely Peixoto Santos <maely.santos@portalsesisp.org.br>

#Manuntencao: 

#------------------------------------------------------------------------------

#Funcionamneto: 

#inicialmente o cli,ao ser executado, realiza HTTP para buscar e exibir o resumo de um artigo 
#utilizando o pacote http.

#Dentro da pasta dartpedia em /home/maely.peixoto/cli, rode o comando dart pub get; deve ser feita a instalacao
#das depedencias do projeto e o pacote http ficara disponivel para o uso do aplicativo 

#Obs. importante ! este aplicativo esta em desenvolvimento e ao longo do tempo o comportamento do aplicativo
#podera mudar 

#--------------------------------------------------------------------------------

#Dicionario do Versionamento:

#V= Versao 

#0= Inicio do versonamento 

#.= Implementacao de versionamento 

#1= Proxima Versao,2, proxima versao, e assim por diante

#--------------------------------------------------------------------------------

#Historico de Versionamento:

#--------------------------------------------------------------------------------

#Versao: 0.0.0

#Data: 24/04/2026
 
#Descricao do codigo: Codigo original....

#Codigo:

#name: cli
#description: A sample command-line application.
##version: 1.0.0
#repository: https://github.com/my_org/my_repo

#environment:
#  sdk: ^3.11.3

# Add regular dependencies here.

#dependencies:
#  path: ^1.9.0

#dev_dependencies:
#  lints: ^6.0.0
#  test: ^1.25.6 
  

#Saida padrão ao executar o codigo:

#Comando: dart pub get

#Saida: Resolving dependencies... 
#Downloading packages... 
# _fe_analyzer_shared 98.0.0 (100.0.0 available)
# analyzer 12.0.0 (13.0.0 available)
# matcher 0.12.19 (0.12.20 available)
#test 1.31.0 (1.31.1 available)
# test_api 0.7.11 (0.7.12 available)
#test_core 0.6.17 (0.6.18 available)
#  vm_service 15.0.2 (15.2.0 available)
#These packages are no longer being depended on:
#- http 1.6.0
#Changed 1 dependency!
#7 packages have newer versions incompatible with dependency constraints.
#Try `dart pub outdated` for more information. 

#--------------------------------------------------------------------------------------------------------------------------


#Versao: 0.0.1

#Data: 25/04/2026

#Descricao do codigo: adicionar a dependência http
#
#Antes de poder fazer requisições HTTP, você precisa adicionar o httppacote como uma dependência ao seu projeto.
#
#Abra o dartpedia/cli/pubspec.yamlarquivo dentro do seu projeto. Este arquivo se chama pubspec e gerencia os metadados, as dependências (como o httppacote) e os recursos do seu projeto Dart.
#
#Localize a dependenciesseção.
#
#Adicione http: ^1.3.0(ou a versão estável mais recente) em dependencies. O ^símbolo permite que versões compatíveis sejam usadas.
#
#dependencies:
#  http: ^1.3.0
#  Salve o pubspec.yamlarquivo.
#
#  Execute o comando dart pub getno seu terminal a partir do dartpedia/clidiretório. Este comando busca a dependência recém-adicionada e a disponibiliza para uso no seu projeto.
#
#  Você deverá ver uma saída semelhante a esta:
#
#  Resolving dependencies...
#  Downloading packages...
#  + http 1.4.0
#    lints 5.1.1 (6.0.0 available)
#    Changed 1 dependency!
#    1 package has newer versions incompatible with dependency constraints.

# Try `dart pub outdated` for more information. 
#
#codigo:

#name: cli
#description: A sample command-line application.
#version: 1.0.0
# repository: https://github.com/my_org/my_repo

#environment:
#  sdk: ^3.11.3

# Add regular dependencies here.
#dependencies:
#   path: ^1.9.0
#   http: ^1.3.0

#dev_dependencies:
#  lints: ^6.0.0
#  test: ^1.25.6

#Saida padrão ao executar o codigo:

#Comando: dart pub get
#
#Saida:resolving dependencies...
#Downloading packages...
#+ http 1.6.0
#  lints 5.1.1 (6.0.0 available)
#  Changed 1 dependency!
#  1 package has newer versions incompatible with dependency constraints.
#  Try `dart pub outdated` for more information.
#
#----------------------------------------------------------------------------------------------------------------------------

#codigo ate aqui:

#Codigo: 

name: cli
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.3

# Add regular dependencies here.
dependencies:
  http: ^1.3.0
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
